# Generated by Django 5.2.3 on 2025-10-29 17:09

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'orgao',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'utilizador',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('edicao', core.models.ProgramaEdicaoField()),
                ('orgao', models.ForeignKey(db_column='orgao_id', on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='core.orgao')),
            ],
            options={
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='GrupoPecas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('programa', models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='core.programa')),
            ],
            options={
                'db_table': 'grupo_pecas',
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='core.categoria')),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='core.grupopecas')),
                ('programa', models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='core.programa')),
                ('utilizador', models.ForeignKey(db_column='utilizador_id', on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='core.utilizador')),
            ],
            options={
                'db_table': 'peca',
            },
        ),
        migrations.AddConstraint(
            model_name='programa',
            constraint=models.UniqueConstraint(fields=('nome', 'orgao'), name='uq_programa_nome_orgao'),
        ),
        migrations.AddConstraint(
            model_name='grupopecas',
            constraint=models.UniqueConstraint(fields=('nome', 'programa'), name='uq_grupo_pecas_nome_programa'),
        ),
    ]
