# Generated by Django 5.2.3 on 2025-10-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exemplo',
        ),
    ]
