# Generated by Django 5.2.3 on 2025-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_exemplo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor')], default='editor', max_length=10),
        ),
    ]
