# Generated by Django 5.2.3 on 2025-11-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_utilizador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='core.grupopecas'),
        ),
    ]
