# Generated by Django 5.2.3 on 2025-12-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_peca_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopecas',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='grupos_pdfs/'),
        ),
    ]
